"""books table

Revision ID: 6094c61fb04c
Revises: 
Create Date: 2020-09-02 17:21:17.304284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6094c61fb04c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_author', table_name='book')
    op.create_index(op.f('ix_book_author'), 'book', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_author'), table_name='book')
    op.create_index('ix_book_author', 'book', ['author'], unique=1)
    # ### end Alembic commands ###
